services:
  cyberflix-server:
    build: .
    container_name: cyberflix-server
    env_file:
      - .env
    ports:
      - "2075:2075"

    command: ["gunicorn", "-t", "600", "-b", "0.0.0.0:2075", "-k", "uvicorn.workers.UvicornWorker", "run:app"]
