version: '3.8'
#! I didnt finish this part, but I would have used this to run the app in a container
services:
  app:
    build: .
    ports:
      - "8000:8000"
    command: ["gunicorn", "run:app", "--timeout", "600", "-b", "0.0.0.0:8000", "--workers", "4"]
